**Importing  following libraries**

In [97]:
import numpy as np     # linear algebra
import pandas as pd    # data processing, CSV file I/O (e.g. pd.read_csv)
from sklearn.preprocessing import LabelEncoder

**Reading dataset**

In [98]:
data = pd.read_csv("matches.csv")

**Display the full summary and return the first 5 rows**

In [99]:
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
id                 756 non-null int64
season             756 non-null int64
city               749 non-null object
date               756 non-null object
team1              756 non-null object
team2              756 non-null object
toss_winner        756 non-null object
toss_decision      756 non-null object
result             756 non-null object
dl_applied         756 non-null int64
winner             752 non-null object
win_by_runs        756 non-null int64
win_by_wickets     756 non-null int64
player_of_match    752 non-null object
venue              756 non-null object
umpire1            754 non-null object
umpire2            754 non-null object
umpire3            119 non-null object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB


id  season        city        date                  team1  \
0   1    2008   Bangalore  18-04-2008  Kolkata Knight Riders   
1   2    2008  Chandigarh  19-04-2008    Chennai Super Kings   
2   3    2008       Delhi  19-04-2008       Rajasthan Royals   
3   4    2008      Mumbai  20-04-2008         Mumbai Indians   
4   5    2008     Kolkata  20-04-2008        Deccan Chargers   

                         team2                  toss_winner toss_decision  \
0  Royal Challengers Bangalore  Royal Challengers Bangalore         field   
1              Kings XI Punjab          Chennai Super Kings           bat   
2             Delhi Daredevils             Rajasthan Royals           bat   
3  Royal Challengers Bangalore               Mumbai Indians           bat   
4        Kolkata Knight Riders              Deccan Chargers           bat   

   result  dl_applied                       winner  win_by_runs  \
0  normal           0        Kolkata Knight Riders          140   
1  normal           0          Chennai Super Kings           33   
2  normal           0             Delhi Daredevils            0   
3  normal           0  Royal Challengers Bangalore            0   
4  normal           0        Kolkata Knight Riders            0   

   win_by_wickets player_of_match                                       venue  \
0               0     BB McCullum                       M Chinnaswamy Stadium   
1               0      MEK Hussey  Punjab Cricket Association Stadium, Mohali   
2               9     MF Maharoof                            Feroz Shah Kotla   
3               5      MV Boucher                            Wankhede Stadium   
4               5       DJ Hussey                                Eden Gardens   

     umpire1         umpire2 umpire3  
0  Asad Rauf     RE Koertzen     NaN  
1  MR Benson      SL Shastri     NaN  
2  Aleem Dar  GA Pratapkumar     NaN  
3   SJ Davis       DJ Harper     NaN  
4  BF Bowden     K Hariharan     NaN

**Fill NA/NaN values**

In [100]:
data['winner'].fillna('Draw', inplace = True)

**Detect missing values in winner column**

In [101]:
data[pd.isnull(data['winner'])]

Empty DataFrame
Columns: [id, season, city, date, team1, team2, toss_winner, toss_decision, result, dl_applied, winner, win_by_runs, win_by_wickets, player_of_match, venue, umpire1, umpire2, umpire3]
Index: []

**Dropping following columns**

In [102]:
New_data = data.drop(["id", "season", "date", "result","dl_applied", "win_by_runs", "win_by_wickets" ,"player_of_match", "umpire1", "umpire2", "umpire3"], axis = 1)

**Return the first 5 rows**

In [103]:
New_data.head()

city                  team1                        team2  \
0   Bangalore  Kolkata Knight Riders  Royal Challengers Bangalore   
1  Chandigarh    Chennai Super Kings              Kings XI Punjab   
2       Delhi       Rajasthan Royals             Delhi Daredevils   
3      Mumbai         Mumbai Indians  Royal Challengers Bangalore   
4     Kolkata        Deccan Chargers        Kolkata Knight Riders   

                   toss_winner toss_decision                       winner  \
0  Royal Challengers Bangalore         field        Kolkata Knight Riders   
1          Chennai Super Kings           bat          Chennai Super Kings   
2             Rajasthan Royals           bat             Delhi Daredevils   
3               Mumbai Indians           bat  Royal Challengers Bangalore   
4              Deccan Chargers           bat        Kolkata Knight Riders   

                                        venue  
0                       M Chinnaswamy Stadium  
1  Punjab Cricket Association Stadium, Mohali  
2                            Feroz Shah Kotla  
3                            Wankhede Stadium  
4                                Eden Gardens

**Replacing Team names with their short forms**

In [104]:
New_data.replace(['Kings XI Punjab', 'Royal Challengers Bangalore','Sunrisers Hyderabad', 'Mumbai Indians', 'Delhi Daredevils', 'Chennai Super Kings','Kolkata Knight Riders', 'Rajasthan Royals', 'Delhi Capitals'], ['KXIP', 'RCB', 'SRH', 'MI', 'DC', 'CSK', 'KKR', 'RR', 'DC'], inplace = True)

**Dropping teams that are not in IPL tournament**

In [105]:
New_data.drop(New_data[New_data['team1'] == 'Gujarat Lions'].index, inplace = True)
New_data.drop(New_data[New_data['team2'] == 'Gujarat Lions'].index, inplace = True)
New_data.drop(New_data[New_data['team1'] == 'Rising Pune Supergiants'].index, inplace = True)
New_data.drop(New_data[New_data['team2'] == 'Rising Pune Supergiants'].index, inplace = True)
New_data.drop(New_data[New_data['team1'] == 'Rising Pune Supergiant'].index, inplace = True)
New_data.drop(New_data[New_data['team2'] == 'Rising Pune Supergiant'].index, inplace = True)
New_data.drop(New_data[New_data['team1'] == 'Deccan Chargers'].index, inplace = True)
New_data.drop(New_data[New_data['team2'] == 'Deccan Chargers'].index, inplace = True)
New_data.drop(New_data[New_data['team1'] == 'Kochi Tuskers Kerala'].index, inplace = True)
New_data.drop(New_data[New_data['team2'] == 'Kochi Tuskers Kerala'].index, inplace = True)
New_data.drop(New_data[New_data['team1'] == 'Pune Warriors'].index, inplace = True)
New_data.drop(New_data[New_data['team2'] == 'Pune Warriors'].index, inplace = True)


**Return the first 5 rows**

In [106]:
New_data.head()

city team1 team2 toss_winner toss_decision winner  \
0   Bangalore   KKR   RCB         RCB         field    KKR   
1  Chandigarh   CSK  KXIP         CSK           bat    CSK   
2       Delhi    RR    DC          RR           bat     DC   
3      Mumbai    MI   RCB          MI           bat    RCB   
5      Jaipur  KXIP    RR        KXIP           bat     RR   

                                        venue  
0                       M Chinnaswamy Stadium  
1  Punjab Cricket Association Stadium, Mohali  
2                            Feroz Shah Kotla  
3                            Wankhede Stadium  
5                      Sawai Mansingh Stadium

**Display the full summary**

In [107]:
New_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 571 entries, 0 to 755
Data columns (total 7 columns):
city             564 non-null object
team1            571 non-null object
team2            571 non-null object
toss_winner      571 non-null object
toss_decision    571 non-null object
winner           571 non-null object
venue            571 non-null object
dtypes: object(7)
memory usage: 35.7+ KB


**Detect missing values in winner column**

In [108]:
New_data[pd.isnull(New_data['city'])]

city team1 team2 toss_winner toss_decision winner  \
402  NaN    MI   RCB         RCB         field    RCB   
403  NaN   KKR    DC         KKR           bat     DC   
407  NaN   CSK    RR          RR         field    CSK   
409  NaN   SRH    DC         SRH           bat    SRH   
410  NaN    MI   CSK          MI           bat    CSK   
415  NaN   RCB  KXIP        KXIP         field   KXIP   
417  NaN   SRH    MI          MI         field    SRH   

                                   venue  
402  Dubai International Cricket Stadium  
403  Dubai International Cricket Stadium  
407  Dubai International Cricket Stadium  
409  Dubai International Cricket Stadium  
410  Dubai International Cricket Stadium  
415  Dubai International Cricket Stadium  
417  Dubai International Cricket Stadium

**Remove missing values. If any NA values are present, drop that row or column.**

In [109]:
New_data = New_data.dropna(how = 'any')

**Return the first 5 rows**

In [110]:
New_data.head()

city team1 team2 toss_winner toss_decision winner  \
0   Bangalore   KKR   RCB         RCB         field    KKR   
1  Chandigarh   CSK  KXIP         CSK           bat    CSK   
2       Delhi    RR    DC          RR           bat     DC   
3      Mumbai    MI   RCB          MI           bat    RCB   
5      Jaipur  KXIP    RR        KXIP           bat     RR   

                                        venue  
0                       M Chinnaswamy Stadium  
1  Punjab Cricket Association Stadium, Mohali  
2                            Feroz Shah Kotla  
3                            Wankhede Stadium  
5                      Sawai Mansingh Stadium

**Returns array of unique team names**

In [111]:
New_data['team1'].unique()

array(['KKR', 'CSK', 'RR', 'MI', 'KXIP', 'RCB', 'DC', 'SRH'], dtype=object)

**Replace Team names with unique values and encoding columns 'city', 'toss_decsion', 'venue' with numeric values**

In [112]:
#Creating a dictionary encode_team

encode_team = {'team1': {'MI':1, 'KKR':2, 'RCB':3, 'CSK':4, 'RR':5, 'KXIP':6, 'DC':7, 'SRH':8},
         'team2': {'MI':1, 'KKR':2, 'RCB':3, 'CSK':4, 'RR':5, 'KXIP':6, 'DC':7, 'SRH':8},
         'toss_winner': {'MI':1, 'KKR':2, 'RCB':3, 'CSK':4, 'RR':5, 'KXIP':6, 'DC':7, 'SRH':8},
         'winner': {'MI':1, 'KKR':2, 'RCB':3, 'CSK':4, 'RR':5, 'KXIP':6, 'DC':7,'SRH':8}
              }

New_data.replace(encode_team, inplace= True)

lab = LabelEncoder()      #convert categorical data, or text data, into numbers

New_data['city'] = lab.fit_transform(New_data['city'])
New_data['toss_decision'] = lab.fit_transform(New_data['toss_decision'])
New_data['venue'] = lab.fit_transform(New_data['venue'])

New_data.head()

city  team1  team2  toss_winner  toss_decision winner  venue
0     2      2      3            3              1      2     15
1     7      4      6            4              0      4     24
2    10      5      7            5              0      7      8
3    21      1      3            1              0      3     35
5    16      6      5            6              0      5     28

**Display array of unique values of winner column**

In [113]:
New_data['winner'].unique()

array([2, 4, 7, 3, 5, 6, 1, 8, 'Draw'], dtype=object)

**Return first 5 rows with reset index**

In [114]:
New_data.head()

city  team1  team2  toss_winner  toss_decision winner  venue
0     2      2      3            3              1      2     15
1     7      4      6            4              0      4     24
2    10      5      7            5              0      7      8
3    21      1      3            1              0      3     35
5    16      6      5            6              0      5     28

**Dropping the index values for which winner value is 'Draw'**

In [115]:
New_data.drop(New_data[New_data['winner'] == 'Draw'].index, inplace = True)

In [116]:
New_data['winner'].unique()

array([2, 4, 7, 3, 5, 6, 1, 8], dtype=object)

**Displaying array of unique values in column 'city'**

In [117]:
New_data['city'].unique()

array([ 2,  7, 10, 21, 16,  8, 19,  5, 22, 12,  6, 13, 17, 18,  4,  1, 11,
       23, 14, 24, 25,  0, 26,  9, 27, 15, 20,  3], dtype=int64)

In [118]:
New_data.reset_index(drop=True, inplace=True)

**Building the feature matrix 'X' and label vector 'Y'**

In [119]:
X = New_data.drop(['winner'], axis = 1)

Y = New_data['winner']

**Training feature matrix and label vector**

In [120]:
x_train = np.array(X.iloc[:550, :])
x_train = x_train.astype('int')
y_train = np.array(Y.iloc[:550])
y_train = y_train.astype('int')

**Printing shape values of feature matrix and label vectors**

In [121]:
X.shape

(561, 6)

In [122]:
Y.shape

(561,)

**Testing feature matrix and label vector**

In [123]:
x_test = X.iloc[550:561,:] 
y_test = Y.iloc[550:561]

**Implementing Logistic Regression Model**

In [124]:
# Importing model

from sklearn.linear_model import LogisticRegression

# Making instance of the Model

logisticRegr = LogisticRegression()

# Train the model using training sets 

logisticRegr.fit(x_train, y_train)

C:\Users\DANISH MEHRA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\DANISH MEHRA\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

**Predicting model**

In [125]:
# Making predictions on the testing set 

predict = logisticRegr.predict(x_test)

**Printing Original Winners**

In [126]:
y_test

550    4
551    1
552    2
553    7
554    3
555    6
556    1
557    1
558    7
559    4
560    1
Name: winner, dtype: object

**Calculating Accuracy of Logistic Regression**

In [127]:
score = 0
for i,each in enumerate(y_test):
    if each == predict[i]:
        score = score + 1
accuracy = (score / len(y_test)) * 100
print(round(accuracy) , "%")

55 %


**Implementing KNN model**

In [128]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors = 3)

knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

**Predicting model**

In [129]:
predict = knn.predict(x_test)
print(predict)

[4 1 2 4 3 6 1 1 5 8 8]


**Calculating Accuracy of KNN**

In [130]:
score = 0
for i,each in enumerate(y_test):
    if each == predict[i]:
        score = score + 1
accuracy = (score / len(y_test)) * 100
print(round(accuracy) , "%")

64 %


**Implementing RandomForestClassifier model**

In [131]:
from sklearn.ensemble import RandomForestClassifier
#x_train = pd.DataFrame(x_train)

rfc = RandomForestClassifier()
rfc.fit(x_train, y_train)

C:\Users\DANISH MEHRA\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

**Predicting Model**

In [132]:
predict = rfc.predict(x_test)

**Calculating Accuracy of Random Forest Classifier**

In [133]:
score = 0
for i,each in enumerate(y_test):
    if each == predict[i]:
        score = score + 1
accuracy = (score / len(y_test)) * 100
print(round(accuracy) , "%")

82 %


In [134]:
# To find out the importance of each feature in determing the outcome class.

print(rfc.feature_importances_)

[0.16291638 0.20642139 0.24773702 0.14012724 0.03329153 0.20950644]


**TKinter Simple GUI for project demonstration**

In [136]:
from tkinter import *
import tkinter

from PIL import ImageTk, Image

window = Tk()
window.geometry("1366x768")
window.title(string = 'AI & ML Workshop Project 2019')

path1 = 'im_1.jpg'
path2 = 'im_2.jpg'
path3 = 'im_3.jpg'
path4 = 'im_4.jpg'
path5 = 'im_5.jpg'
path6 = 'im_6.jpg'
path7 = 'im_7.jpg'
path8 = 'im_8.jpg'
path9 = 'im_9.jpg'


img1 = ImageTk.PhotoImage(Image.open(path1))
img2 = ImageTk.PhotoImage(Image.open(path2))
img3 = ImageTk.PhotoImage(Image.open(path3))
img4 = ImageTk.PhotoImage(Image.open(path4))
img5 = ImageTk.PhotoImage(Image.open(path5))
img6 = ImageTk.PhotoImage(Image.open(path6))
img7 = ImageTk.PhotoImage(Image.open(path7))
img8 = ImageTk.PhotoImage(Image.open(path8))
img9 = ImageTk.PhotoImage(Image.open(path9))

img = [img1, img2, img3, img4, img5, img6, img7, img8, img9]

frame1 = Frame(window)
frame1.pack(side = TOP, fill = X)

frame2 = Frame(window)
frame2.pack(side = TOP, fill = X)

frame3 = Frame(window)
frame3.pack(side = TOP, fill = X)

frame4 = Frame(window)
frame4.pack(side = TOP, fill = X)

frame5 = Frame(window)
frame5.pack(side = TOP, fill = X)

frame6 = Frame(window)
frame6.pack(side = TOP, fill = X)
 
label1 = tkinter.Label(frame1, text = "Welcome to IPL Winner Predictor!",font=("Arial Bold",16))
label1.pack(side = TOP, fill =X)
label2 = tkinter.Label(frame1, text = "We have used a dataset of IPL history from 2008 to 2019. The data set has been extracted from kaggle !", font=("Helvetica",14))
label2.pack(side = TOP, fill = X)

label3 = tkinter.Label(frame2, text = "Let us first explore the original data set")
label3.grid(row= 1, column = 0, padx= 10, pady =10)


def call(image_number):
    win1 = Toplevel(window)
    panel = tkinter.Label(win1, image = img[image_number])
    panel.pack(side = "bottom", fill = "both", expand = "yes")
    

button1 = tkinter.Button(frame2, text="Original Data Set", command = lambda : call(0))
button1.grid(row=1, column = 2)
    
label4 =  tkinter.Label(frame3, text = "    Now coming to the essential part of cleaning our data.")
label4.grid(row= 0, column = 0, sticky = "W")
label5 =  tkinter.Label(frame3, text = "    We removed the drawn matches and also the non-existant teams for IPL 2020")
label5.grid(row= 1, column = 0, sticky = "W")
label6 =  tkinter.Label(frame3, text = "    The resultant dataset after multi labelling and cleaning has a shape of 561 X 7")
label6.grid(row= 2, column = 0, sticky = "W")

button2 = tkinter.Button(frame3, text="Dataset after cleaning",command = lambda : call(1))
button2.grid(row= 2, column = 1)
 

label4 =  tkinter.Label(frame4, text = "    Data is finally ready for training !")
label4.grid(row= 1, column = 0)
button3 = tkinter.Button(frame4, text="x_train",command = lambda : call(2))
button3.grid(row= 2, column = 0, padx =5, pady = 5)
button4 = tkinter.Button(frame4, text="y_train",command = lambda : call(3))
button4.grid(row= 2, column = 1, padx = 5, pady = 5)
button5 = tkinter.Button(frame4, text="x_test", command = lambda : call(4))
button5.grid(row= 3, column = 0, padx = 5, pady = 5)
button6 = tkinter.Button(frame4, text="y_test", command = lambda : call(5))
button6.grid(row= 3, column = 1, padx=5, pady = 5)


label7 =  tkinter.Label(frame5, text = "    Following Machine Learning Models were used. Click on each to see the results and accuracy!")
label7.grid(row= 0, column = 0)
button7 = tkinter.Button(frame5, text="Logistic Regression", command = lambda : call(6))
button7.grid(row= 0, column = 1, padx = 5, pady = 5)
button8 = tkinter.Button(frame5, text="K-nearest Neighbors", command = lambda : call(7))
button8.grid(row= 0, column = 2, padx = 5, pady = 5)
button9 = tkinter.Button(frame5, text="Random Forest Classifier", command = lambda : call(8))
button9.grid(row= 0, column = 3, padx =5, pady = 5)



window.mainloop()

